### ISSUE TITLE
无法修改+自动刷新+搜索按钮

### ISSUE THREAD

**Issue by Qsirman** [scatl/UestcBBS-MVP#1]
1. 某些可修改的帖子在客户端没有修改按钮
2. 评论完后页面不刷新就看不到刚才的评论，虽然是河畔本身的问题，但希望可以解决一下，或者提供一个选项
3. 搜索按钮希望可以放在首页或者在首页也复制一个，第一次找搜索按钮感觉找了半天

**Comment by scatl** [comment]
1、帖子修改涉及到图片，比较麻烦，需要点时间
2、计划下个版本优化一下
3、会在首页添加搜索按钮
