### ISSUE TITLE
请问阁下是在校学生吗

### ISSUE THREAD

**Issue by cuisiwang** [scatl/UestcBBS-MVP#15]
我们很好奇您是什么身份，是在校学生吗？还是就职人员等。
清水河畔是由星辰工作室运营的，但我们未听闻有安卓app的开发与维护，所以请问您方便透露一下您的相关信息或与我们联系嘛？
感激不尽！您可以联系这个邮箱：cuisiwanf@163.com

**Comment by scatl** [comment]
你们是？有问题通过这个邮箱联系吧：sca_tl@foxmail.com

**Comment by scatl** [comment]
> 我们很好奇您是什么身份，是在校学生吗？还是就职人员等。 清水河畔是由星辰工作室运营的，但我们未听闻有安卓app的开发与维护，所以请问您方便透露一下您的相关信息或与我们联系嘛？ 感激不尽！您可以联系这个邮箱：[cuisiwanf@163.com](mailto:cuisiwanf@163.com)

你们是？有问题通过这个邮箱联系吧：[sca_tl@foxmail.com](mailto:sca_tl@foxmail.com)
