### ISSUE TITLE
我想问一下，首页跑马灯下面的导航在哪里修改啊？

### ISSUE THREAD

**Issue by tokpig** [scatl/UestcBBS-MVP#5]
用的安米的moment桥接包，接口好像都对，域名一修改打包就好了，但是那个导航不知道在哪里改。

**Comment by scatl** [comment]
你是指轮播图下面的每日答题等功能么？这个是我自己添加的，没有对应的接口

**Comment by scatl** [comment]
> 用的安米的moment桥接包，接口好像都对，域名一修改打包就好了，但是那个导航不知道在哪里改。

你是指轮播图下面的每日答题等功能么？这个是我自己添加的，没有对应的接口

**Comment by tokpig** [comment]
> > 用的安米的moment桥接包，接口好像都对，域名一修改打包就好了，但是那个导航不知道在哪里改。
> 
> 你是指轮播图下面的每日答题等功能么？这个是我自己添加的，没有对应的接口

已经改好了，但是那个热门不显示，好像是接口问题？还有那个淘贴（能加载专辑，但是点击后显示数据解析失败）

**Comment by scatl** [comment]
> > > 用的安米的moment桥接包，接口好像都对，域名一修改打包就好了，但是那个导航不知道在哪里改。
> > 
> > 
> > 你是指轮播图下面的每日答题等功能么？这个是我自己添加的，没有对应的接口
> 
> 已经改好了，但是那个热门不显示，好像是接口问题？还有那个淘贴（能加载专辑，但是点击后显示数据解析失败）

应该是河畔插件版本过低的原因
