### ISSUE TITLE
河畔恢复外网访问了！！

### ISSUE THREAD

**Issue by syc0000000** [scatl/UestcBBS-MVP#63]
如果可以的话，速速维护

**Comment by scatl** [comment]
已经一年了，屎山代码不想再维护了。鉴于河畔已经改版了，可能会重新写一个，敬请期待😊

**Comment by scatl** [comment]
> 如果可以的话，速速维护


已经一年了，屎山代码不想再维护了。鉴于河畔已经改版了，可能会重新写一个，敬请期待😊
